# mpv = "C:\\path\\of\\mpv.com"

# Optional, Type: String
# The path of mpv binary
# Default value:
# - Linux: mpv
# - Windows: mpv.com

# ytdl = "C:\\path\\of\\yt-dlp.exe"

# Optional, Type: String
# The path of yt-dlp binary
# Default value:
# - Linux: yt-dlp
# - Windows: yt-dlp.exe

# proxy = "http://example.com:8080"

# Optional, Type: String
# The proxy server address

# For Windows users:
#   The path can be "C:\\folder\\some.exe" or "C:/folder/some.exe"
