#mpv = "C:\\path\\of\\mpv.com"
# Optional, Type: String
# The path of mpv executable binary
# Default value:
# - Linux: mpv
# - Windows: mpv.com

#ytdl = "C:\\path\\of\\yt-dlp.exe"
# Optional, Type: String
# The path of yt-dlp executable binary

#proxy = "http://example.com:8080"
# Optional, Type: String
# HTTP(S) proxy server address

# For Windows users:
#   - The path can be "C:\\folder\\some.exe" or "C:/folder/some.exe"
#   - The path is an executable binary file, not a directory
