#mpv = "/path/of/mpv"
# Optional, Type: String
# The path of mpv binary
# Default value:
# - Linux: mpv
# - Windows: mpv.com

#ytdl = "/path/of/ytdl"
# Optional, Type: String
# The path of yt-dlp binary

#proxy = "http://example.com:8080"
# Optional, Type: String
# HTTP(S) proxy server address
